### NUMPY

-a library for representing with working with large arrays. 
-provides useful tools for programming.
-great to use for consistent computed data.

In [6]:
#Ex:
import numpy as np

### Indexing
#### We can create a numpy array by passing a list ot the np.array function:

In [7]:
a=np.array([1,2,3])

In [8]:
a

array([1, 2, 3])

In [9]:
print(a)

[1 2 3]


#### We can create a multi-dimen. array by passing a list of lists to the array function:

In [10]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


##referencing elements in numpy arrays at the basic is the smae as referencing elements in python lists.

In [13]:
a[0]

1

In [14]:
print(a)

[1 2 3]


How do you pull out things from multidimensions array (nested lists), 
#example: to get element at the second column in second row:
        

In [16]:
matrix[1,1]

5

In [18]:
#to remember:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
matrix[1: :2] 
#1. give me rows starting from index postions 1 onwards
#2. give me rows up to (but not including) index positions 2

array([[4, 5, 6]])

Arrays can also index with a boolean sequence:

In [20]:
a

array([1, 2, 3])

In [21]:
a[[True, False, True]] #this is saying; give me the first of array, don't give me second, give me last

array([1, 3])

In [22]:
should_include_elements_a = [True, False, True]#here's how you can link the function with the boolean
a[should_include_elements_a]

array([1, 3])

### Vectorized Operations

#### If we wanted to add 1 to every element in a list. Example:

In [23]:
original_array = [1,2,3,4,5] ##try will allow us to test out lines of code
try:
    original_array + 1
except TypeError as e:
    print('An Error Occured!')
    print(f'TypeError: {e}')

An Error Occured!
TypeError: can only concatenate list (not "int") to list


In [25]:
#Why the error??? Python thought that we were trying to do: [1,2,3,4,5] + [1]

In [26]:
#Let's try writing a loop...

In [27]:
original_array = [1,2,3,4,5]
array_add_one = []
for n in original_array:
    array_add_one.append(n+1)
    print(array_add_one)

[2]
[2, 3]
[2, 3, 4]
[2, 3, 4, 5]
[2, 3, 4, 5, 6]


#### Vectorizing means that operatirons are automatically applied to every element in that array. 

In [29]:
numpy_array = np.array([1,2,3,4,5])
numpy_array + 1

array([2, 3, 4, 5, 6])

In [30]:
print(numpy_array +2)

[3 4 5 6 7]


In [31]:
#Can work with basic math too:

In [33]:
my_array = np.array([-3, 0, 3, 16])

print(f'my_array      == {my_array}')
print(f'my_array - 5  == {my_array - 5}')
print(f'my_array * 4  == {my_array * 4}')
print(f'my_array / 2  == {my_array / 2}')
print(f'my_array ** 2 == {my_array ** 2}')
print(f'my_array % 2  == {my_array % 2}')

my_array      == [-3  0  3 16]
my_array - 5  == [-8 -5 -2 11]
my_array * 4  == [-12   0  12  64]
my_array / 2  == [-1.5  0.   1.5  8. ]
my_array ** 2 == [  9   0   9 256]
my_array % 2  == [1 0 1 0]


#### Same applies to comparison operators...

In [34]:
my_array = np.array([-3, 0, 3, 16])

print(f'my_array       == {my_array}')
print(f'my_array == -3 == {my_array == -3}')
print(f'my_array >= 0  == {my_array >= 0}')
print(f'my_array < 10  == {my_array < 10}')

my_array       == [-3  0  3 16]
my_array == -3 == [ True False False False]
my_array >= 0  == [False  True  True  True]
my_array < 10  == [ True  True  True False]


In [35]:
#if vectorizing comparison operators as boolean...

print(my_array > 0)

[False False  True  True]


In [36]:
#And if we can give an array some booleans to select the values we want to return...

In [37]:
my_array[[False, False, True, True]]

array([ 3, 16])

In [39]:
#Then we can "give" an array a condition to select our values for us!

In [41]:
#example: give me all the positive numbers in my_array
my_array[my_array > 0]

array([ 3, 16])

### In-depth Example:

In [42]:
my_array[my_array % 2 == 0]

array([ 0, 16])

In [44]:
my_array

array([-3,  0,  3, 16])

In [43]:
#
my_array % 2

array([1, 0, 1, 0])

In [45]:
# Each element of the array % 2
result = my_array % 2
print(f"My Array:              {my_array}")
print(f"My Array % 2 (Result): {result}")

My Array:              [-3  0  3 16]
My Array % 2 (Result): [1 0 1 0]


In [48]:
# Does each element % 2 == 0?
print(f"My Array:                   {my_array}")
print(f"My Array % 2 (Result):      {result}")
print(f"result == 0:                {result == 0}")

My Array:                   [-3  0  3 16]
My Array % 2 (Result):      [1 0 1 0]
result == 0:                [False  True False  True]


In [49]:
#Lastly, we use this array of boolean values to index into the original array, which gives us only the values that are 
#evenly divisible by 2.

In [50]:
step_1 = my_array % 2
step_2 = step_1 == 0
step_3 = my_array[step_2]

step_3

array([ 0, 16])

In [51]:
#can we see an elements that is  0 < AND > 10

In [55]:
my_array

array([-3,  0,  3, 16])

In [58]:
my_array[(my_array >= 0) & (my_array <10)] #and statement &

array([0, 3])

In [59]:
my_array [(my_array <0) | (my_array > 3)] #or statement |

array([-3, 16])

### Array Creation: was to create those arrays:

#### - np.random.randn : can be used to create an array of specific len
#of random numbers drawn from normal std of normal distribution.

In [63]:
np.random.randn(10)

array([ 1.01662897, -1.70023289, -1.12476382, -1.08314851, -1.50738774,
        1.44228056, -0.33757226,  0.03897078,  1.25369524,  0.71259269])

In [64]:
#majority of output mimics the standard normal distribution (1--1)

In [66]:
np.random.randn(3,4)#rows, columns

array([[ 0.00655639, -1.35998576,  1.36960283,  1.11062413],
       [ 0.51823348, -1.0067112 ,  1.54801603, -1.60436993],
       [ 1.31607076, -1.90890354, -0.14255077,  0.81424786]])

In [67]:
##if we wish to obtain original values from z-score of normal distribution
#we need to apply some arithmetic.

#to convert, we will need to multiply by the stdev and add the mean

In [69]:
z_scores_iq = np.random.randn(20)
z_scores_iq

array([ 1.01963957, -0.30806997, -0.50517179, -1.03741093, -1.4657384 ,
        1.54514409, -0.37709038, -0.41636352,  0.01874013, -0.48297988,
        0.46872511, -0.92711966,  0.20794398, -0.04258093, -1.28124569,
       -0.37350751, -2.57059635,  1.67119   ,  0.13449677,  0.3766945 ])

In [72]:
μ = 100 # If we have a mean of 100...
σ = 30 # ...and a standard deviation of 30...

raw_iq_scores= σ * z_scores_iq + μ # We can derive the unscaled values
raw_iq_scores

array([130.58918707,  90.75790078,  84.84484635,  68.877672  ,
        56.02784797, 146.35432283,  88.68728852,  87.50909451,
       100.56220393,  85.51060368, 114.0617534 ,  72.1864103 ,
       106.23831946,  98.72257222,  61.56262922,  88.79477474,
        22.88210963, 150.13569993, 104.03490316, 111.30083512])

#### -np.zeros, np.ones, np.full

In [76]:
#gives us alot of 00000 in a row. 
#can be used as placeholders for things to be added onto later

In [74]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [75]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [77]:
np.full(3,17)

array([17, 17, 17])

In [78]:
np.zeros((2,3))#passing a tuple

array([[0., 0., 0.],
       [0., 0., 0.]])

In [79]:
np.ones((5,5))#5 rows and 5 columns

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [80]:
np.full((3,4), 17)

array([[17, 17, 17, 17],
       [17, 17, 17, 17],
       [17, 17, 17, 17]])

### np.arange

#### similar to range. Takes an argument and generates a range from zero up to it, but not including the passed number.

In [82]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
##also as a step:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [85]:
##can also handle decimal number

In [86]:
np.arange(3,5,0.5)

array([3. , 3.5, 4. , 4.5])

### np.linspace

#### method that creates a range of numbers between a minimum and maximum
#### uses a set of number of elements

In [87]:
# min: 1, max: 10, length: 4
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [88]:
# min: 1, max: 10, length: 7
np.linspace(1, 10, 7)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

### Array Methods

#### some built-in methods for ease to math operations.

### .min

In [89]:
a = np.array([1, 2, 3, 4, 5])

In [90]:
a.min()

1

### .max

In [91]:
a.max()

5

### .mean

In [92]:
a.mean()

3.0

### .sum

In [93]:
a.sum()

15

### .std

In [94]:
a.std()

1.4142135623730951