### Use the following code for the questions below:

In [1]:
# a = np.array([4,10,12,23,-2,-1,0,0,0,-6,3,-7])

### 1) How many negative numbers are there?

In [2]:
import numpy as np

a = np.array([4,10,12,23,-2,-1,0,0,0,-6,3,-7])

np.sum(np.array(a)< 0)

4

In [3]:
##other way:
(len(a[a > 0]))

5

In [4]:
###in class example: .size counts the number of values in an array, regardless of nesting
a[a<0].size

4

### 2) How many positive numbers are there?

In [5]:
np.sum(np.array(a)>0)

5

In [6]:
### other
(len(a[a>0]))

5

In [7]:
##Class example:
a[a>0].size

5

### 3) How many even positive numbers are there?

In [8]:
(len(a[(a>0) & (a % 2== 0) ]))

3

### 4) If you were to add 3 to each data point, how many positive numbers would there be?

In [9]:
len(a[(a+3) & (a>0)])

12

In [10]:
a_plus_three= a + 3

In [11]:
np.sum(np.array(a_plus_three)>0)

10

In [12]:
len(a[(a +3)>0]) ## There are 10 positive numbers

10

In [13]:
#_________class example:_______________
add_three = a + 3
add_three[add_three > 0]

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

In [14]:
add_three[add_three > 0].size

10

### 5) If you squared each number, what would the new mean and standard deviation be?

In [15]:
a**2

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [16]:
np.mean(a**2) ##new mean is: 74

74.0

In [17]:
np.std(a**2) ## new stddev is 144.0243035046516

144.0243035046516

### 6) Centering to find the new mean. 

In [18]:
a-(np.mean(a))

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

#####checking my work......

In [19]:
 np.mean(a) #mean of all data points...will subtract 3 from each point

3.0

In [20]:
centered_array =a-(np.mean(a)) ##renamed to check that new mean is 0

In [21]:
print(centered_array)

[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


In [22]:
np.mean(centered_array) #checked ✅ 

0.0

In [23]:
#___________class example_______________

In [24]:
centered = a - a.mean()
centered

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

### 7) Calculate the z-score for each data point. 

In [25]:
(a - np.mean(a)) / np.std(a) # taking a for each data point and using the numpy mean and stddev functions

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

### 8) More Numpy Practice

### Set Up 1): 

#### Use python's built in functionality/operators to determine the following:
#### Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [26]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [27]:
sum_of_a = sum(a)

In [28]:
sum_of_a #checking....

55

#### Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [29]:
min_of_a = min(a)

In [30]:
min_of_a ##Checking

1

#### Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [31]:
max_of_a = max(a)

In [32]:
max_of_a ###checking

10

#### Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [33]:
mean_of_a = sum(a)/ len(a)

In [34]:
mean_of_a ##checking

5.5

#### Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [35]:
def product(x):  #creating a function to multiply all numbers in array
    n = 1
    for i in x:
        n *= i
    return n

In [36]:
product_of_a = product(a) ###then insert array a and rename to variable name asked for

In [37]:
product_of_a  ##here we go!

3628800

##### or.......

In [38]:

product_of_a = 1
for n in a:
    product_of_a *=n

product_of_a

3628800

#### Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [39]:
squares_of_a = [n ** 2 for n in a]

In [40]:
squares_of_a 

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

#### Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [41]:
odds_in_a = [n for n in a if n % 2 !=0] ##moving through the line of statements

In [42]:
odds_in_a

[1, 3, 5, 7, 9]

#### Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [43]:
evens_in_a = [n for n in a if n % 2 == 0]

In [44]:
evens_in_a

[2, 4, 6, 8, 10]

### Set Up 2:

In [45]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

b=np.array(b)

#### Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 
##**Hint, you'll first need to make sure that the "b" variable is a numpy array**

In [46]:
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

In [47]:
sum_of_b #checking the output

33

In [48]:
np.sum(b)###answer

33

#### Exercise 2 - refactor the following to use numpy. 

In [49]:
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

In [50]:
min_of_b

3

In [51]:
np.min(b)

3

#### Exercise 3 - refactor the following maximum calculation to find the answer with numpy.

In [52]:
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [53]:
max_of_b

8

In [54]:
np.max(b)

8

#### Exercise 4 - refactor the following using numpy to find the mean of b

In [55]:
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [56]:
mean_of_b

5.5

In [57]:
np.mean(b)

5.5

#### Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

In [58]:
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

In [59]:
product_of_b

20160

In [60]:
np.product(b)

20160

#### Exercise 6 - refactor the following to use numpy to find the list of squares 

In [61]:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

In [62]:
squares_of_b

[9, 16, 25, 36, 49, 64]

In [63]:
np.square(b)

array([[ 9, 16, 25],
       [36, 49, 64]])

#### Exercise 7 - refactor using numpy to determine the odds_in_b

In [64]:
#odds_in_b = []
#for row in b:
    #for number in row:
        #if(number % 2 != 0):
            #odds_in_b.append(number)

In [65]:
#odds_in_b

In [66]:
odds_in_b = b[b % 2 != 0]

In [67]:
odds_in_b

array([3, 5, 7])

#### Exercise 8 - refactor the following to use numpy to filter only the even numbers

In [68]:
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

In [69]:
evens_in_b

[4, 6, 8]

In [70]:
evens_in_b = b[b % 2 == 0]

In [71]:
evens_in_b

array([4, 6, 8])

#### Exercise 9 - print out the shape of the array b.

In [72]:
b.shape

(2, 3)

####  Exercise 10 - transpose the array b.

In [73]:
b.T

array([[3, 6],
       [4, 7],
       [5, 8]])

#### Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [74]:
b.flatten()

array([3, 4, 5, 6, 7, 8])

#### Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [76]:
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

### SET UP 3:

In [81]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

c = np.array(c)

####  Exercise 1 - Find the min, max, sum, and product of c.

In [85]:
c.min()

1

In [86]:
c.max()

9

In [93]:
c.sum()

45

In [95]:
np.product(c)

362880

#### Exercise 2 - Determine the standard deviation of c.

In [97]:
c.std()

2.581988897471611

#### Exercise 3 - Determine the variance of c.

In [98]:
c.var()

6.666666666666667

#### Exercise 4 - Print out the shape of the array c

In [101]:
c.shape

(3, 3)

#### Exercise 5 - Transpose c and print out transposed result.

In [102]:
c.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

#### Exercise 6 - Get the dot product of the array c with c.

In [104]:
c.dot(c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

#### Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [126]:
transpose_c = sum(c.T * c)

sum(transpose_c)

261

#### Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [127]:
c_times_c = product(c.T*c)

In [128]:
c_times_c

array([  168,  9600, 81648])

In [129]:
product(c_times_c)

131681894400

### SET UP 4:

In [137]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

d = np.array(d)

#### Exercise 1 - Find the sine of all the numbers in d

In [140]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

#### Exercise 2 - Find the cosine of all the numbers in d

In [141]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

#### Exercise 3 - Find the tangent of all the numbers in d

In [142]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

#### Exercise 4 - Find all the negative numbers in d

In [173]:
neg_num = np.array([np.array(d)<0])

In [174]:
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [175]:
neg_num

array([[[False, False, False, False, False, False],
        [False,  True,  True, False, False, False],
        [False, False,  True, False,  True, False]]])