### Use the following code for the questions below:

In [1]:
# a = np.array([4,10,12,23,-2,-1,0,0,0,-6,3,-7])

### 1) How many negative numbers are there?

In [169]:
import numpy as np

a = np.array([4,10,12,23,-2,-1,0,0,0,-6,3,-7])

np.sum(np.array(a)< 0)

4

In [35]:
##other way:
(len(a[a > 0]))

5

In [171]:
###in class example: .size counts the number of values in an array, regardless of nesting
a[a<0].size

4

### 2) How many positive numbers are there?

In [28]:
np.sum(np.array(a)>0)

5

In [38]:
### other
(len(a[a>0]))

5

In [173]:
##Class example:
a[a>0].size

5

### 3) How many even positive numbers are there?

In [42]:
(len(a[(a>0) & (a % 2== 0) ]))

3

### 4) If you were to add 3 to each data point, how many positive numbers would there be?

In [62]:
len(a[(a+3) & (a>0)])

12

In [63]:
a_plus_three= a + 3

In [66]:
np.sum(np.array(a_plus_three)>0)

10

In [67]:
len(a[(a +3)>0]) ## There are 10 positive numbers

10

In [174]:
#_________class example:_______________
add_three = a + 3
add_three[add_three > 0]

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

In [180]:
add_three[add_three > 0].size

10

### 5) If you squared each number, what would the new mean and standard deviation be?

In [68]:
a**2

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [70]:
np.mean(a**2) ##new mean is: 74

74.0

In [71]:
np.std(a**2) ## new stddev is 144.0243035046516

144.0243035046516

### 6) Centering to find the new mean. 

In [75]:
a-(np.mean(a))

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

#####checking my work......

In [74]:
 np.mean(a) #mean of all data points...will subtract 3 from each point

3.0

In [85]:
centered_array =a-(np.mean(a)) ##renamed to check that new mean is 0

In [86]:
print(centered_array)

[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


In [87]:
np.mean(centered_array) #checked ✅ 

0.0

In [181]:
#___________class example_______________

In [182]:
centered = a - a.mean()
centered

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

### 7) Calculate the z-score for each data point. 

In [81]:
(a - np.mean(a)) / np.std(a) # taking a for each data point and using the numpy mean and stddev functions

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

### 8) More Numpy Practice

### Set Up 1): 

#### Use python's built in functionality/operators to determine the following:
#### Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [189]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [93]:
sum_of_a = sum(a)

In [92]:
sum_of_a #checking....

55

#### Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [94]:
min_of_a = min(a)

In [95]:
min_of_a ##Checking

1

#### Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [98]:
max_of_a = max(a)

In [99]:
max_of_a ###checking

10

#### Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [104]:
mean_of_a = sum(a)/ len(a)

In [102]:
mean_of_a ##checking

5.5

#### Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [126]:
def product(x):  #creating a function to multiply all numbers in array
    n = 1
    for i in x:
        n *= i
    return n

In [127]:
product_of_a = product(a) ###then insert array a and rename to variable name asked for

In [128]:
product_of_a  ##here we go!

3628800

##### or.......

In [190]:

product_of_a = 1
for n in a:
    product_of_a *=n

product_of_a

3628800

#### Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [132]:
squares_of_a = [n ** 2 for n in a]

In [133]:
squares_of_a 

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

#### Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [137]:
odds_in_a = [n for n in a if n % 2 !=0] ##moving through the line of statements

In [138]:
odds_in_a

[1, 3, 5, 7, 9]

#### Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [139]:
evens_in_a = [n for n in a if n % 2 == 0]

In [140]:
evens_in_a

[2, 4, 6, 8, 10]

### Set Up 2:

In [197]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

#### Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 
##**Hint, you'll first need to make sure that the "b" variable is a numpy array**

In [192]:
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

In [193]:
sum_of_b #checking the output

33

In [194]:
np.sum(b)###answer

33

#### Exercise 2 - refactor the following to use numpy. 

In [146]:
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

In [147]:
min_of_b

3

In [148]:
np.min(b)

3

#### Exercise 3 - refactor the following maximum calculation to find the answer with numpy.

In [150]:
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [152]:
max_of_b

8

In [151]:
np.max(b)

8

#### Exercise 4 - refactor the following using numpy to find the mean of b

In [153]:
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [154]:
mean_of_b

5.5

In [155]:
np.mean(b)

5.5

#### Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

In [156]:
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

In [157]:
product_of_b

20160

In [158]:
np.product(b)

20160

#### Exercise 6 - refactor the following to use numpy to find the list of squares 

In [159]:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

In [160]:
squares_of_b

[9, 16, 25, 36, 49, 64]

In [161]:
np.square(b)

array([[ 9, 16, 25],
       [36, 49, 64]])

#### Exercise 7 - refactor using numpy to determine the odds_in_b

In [203]:
b[b % 2 != 0]

TypeError: unsupported operand type(s) for %: 'list' and 'int'